routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::resources([
        'clients' => 'ClientController',
        'products' => 'ProductController',
        'deliveryNotes' => 'DeliveryNoteController'
    ]);

    Route::apiResource('api/clients', 'API\ClientController')->names('api.clients');
});

app/DeliveryNote.php
<?php

namespace App;

use App\Events\DeliveryNoteCreated;
use Illuminate\Database\Eloquent\Model;

class DeliveryNote extends Model
{
    protected $fillable = ['client_id', 'product_id', 'quantity'];

    protected $dispatchesEvents = [
        'saved' => DeliveryNoteCreated::class
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function product()
    {
        return $this->belongsTo(Product::class);
    }

    public function gettotalPriceAttribute()
    {
        return number_format(($this->product->price * $this->quantity), 2);
    }
}

app/Http/Controllers/DeliveryNoteController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\DeliveryNote;
use App\Http\Requests\StoreDeliveryNoteRequest;
use App\Product;

class DeliveryNoteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('delivery_note.index', [
            'notes' => DeliveryNote::with(['client', 'product'])->get(),
        ]);
    }

    public function create()
    {
        return view('delivery_note.create', [
            'clients'  => Client::pluck('name', 'id'),
            'products' => Product::pluck('name', 'id'),
        ]);
    }

    public function store(StoreDeliveryNoteRequest $request)
    {
        $input = $request->validated();
        $product = Product::find($input['product_id']);

        if( ! $product->haveInStock($input['quantity'])){
            return redirect()->back()
                ->with('error', 'Product out of stock')
                ->withInput();
        }

        DeliveryNote::create($input);
        return redirect()->route('deliveryNotes.index')->with('success', 'DeliveryNote created');
    }

    public function destroy(DeliveryNote $deliveryNote)
    {
        $deliveryNote->delete();

        return redirect()->route('deliveryNotes.index')->with('success', 'DeliveryNote deleted');
    }
}

resources/views/delivery_note/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Add new DeliveryNote</h5>
            <hr>
            {{ Form::open(['route' => 'deliveryNotes.store']) }}
            <div class="form-group row">
                <label for="client" class="col-sm-2 col-form-label ">Client</label>
                <div class="col-sm-8">
                    {{ Form::select('client_id', $clients, null, ['class' => 'form-control', 'placeholder' => 'Pick a client...', 'required' => 'required']) }}
                </div>
            </div>

            <div class="form-group row">
                <label for="product" class="col-sm-2 col-form-label ">Product</label>
                <div class="col-sm-8">
                    {{ Form::select('product_id', $products, null, ['class' => 'form-control', 'placeholder' => 'Pick a product...', 'required' => 'required']) }}
                </div>
            </div>

            <div class="form-group row">
                <label for="quantity" class="col-sm-2 col-form-label ">Quantity</label>
                <div class="col-sm-8">
                    {{ Form::number('quantity', null, ['class' => 'form-control']) }}
                </div>
            </div>
            <hr>
            <div class="form-group row">
                <div class="col-sm-8 offset-sm-2">
                    <button type="submit" class="btn btn-success">Save</button>
                    <a href="{{ route('deliveryNotes.index') }}" class="btn btn-secondary">Cancel</a>
                </div>
            </div>
            {{ Form::close() }}
        </div>
    </div>
@endsection

resources/views/delivery_note/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-8">
                    <h5 class="card-title">DeliveryNote List</h5>
                </div>
                <div class="col-4 text-right">
                    <a href="{{ route('deliveryNotes.create') }}" class="btn btn-sm btn-primary">Add Delivery Note</a>
                </div>
            </div>

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Client</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Total Price</th>
                    <th>Created</th>
                    <th class="text-right">Actions</th>
                </tr>
                </thead>

                <tbody>
                @foreach($notes as $note)
                    <tr>
                        <td>{{ '#' . $note->id }}</td>
                        <td><a href="{{ route('clients.edit', $note->client->id) }}">{{ $note->client->name }}</a></td>
                        <td><a href="{{ route('products.edit', $note->product->id) }}">{{ $note->product->name }}</a></td>
                        <td>{{ $note->quantity }}</td>
                        <td>{{ $note->totalPrice }}</td>
                        <td>{{ $note->created_at }}</td>
                        <td class="text-right">
                            <form action="{{ route('deliveryNotes.destroy', $note->id) }}" method="post" class="d-inline">
                                @method('delete')
                                @csrf
                                <button type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection